CREATE TABLE IF NOT EXISTS hydrological_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(120) NOT NULL,
    source_resource_id VARCHAR(80) NOT NULL,
    source_record_id BIGINT NOT NULL,
    station_id VARCHAR(64) NOT NULL,
    station_name VARCHAR(200) NOT NULL,
    river_name VARCHAR(200),
    state_name VARCHAR(120),
    district_name VARCHAR(160),
    latitude DOUBLE PRECISION CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    longitude DOUBLE PRECISION CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    geometry geography(Point, 4326) GENERATED ALWAYS AS (
        CASE
            WHEN latitude IS NULL OR longitude IS NULL THEN NULL::geography
            ELSE ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography
        END
    ) STORED,
    water_level DOUBLE PRECISION,
    discharge DOUBLE PRECISION,
    rainfall DOUBLE PRECISION,
    observation_time TIMESTAMPTZ NOT NULL,
    fetched_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_hydro_source_station_observation UNIQUE (source, station_id, observation_time),
    CONSTRAINT uq_hydro_source_resource_record UNIQUE (source_resource_id, source_record_id),
    CONSTRAINT ck_hydro_coordinates_paired CHECK ((latitude IS NULL) = (longitude IS NULL))
);

CREATE INDEX IF NOT EXISTS ix_hydro_station_observation ON hydrological_observations (station_id, observation_time DESC);
CREATE INDEX IF NOT EXISTS ix_hydro_source_fetched ON hydrological_observations (source, fetched_at DESC);
CREATE INDEX IF NOT EXISTS ix_hydro_geometry ON hydrological_observations USING GIST (geometry);
