CREATE TABLE IF NOT EXISTS weather_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_id VARCHAR(100) NOT NULL,
    station_name VARCHAR(160) NOT NULL,
    source VARCHAR(64) NOT NULL DEFAULT 'open-meteo',
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    location geography(Point, 4326) GENERATED ALWAYS AS (
        ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography
    ) STORED,
    temperature_c DOUBLE PRECISION,
    humidity_percent DOUBLE PRECISION CHECK (humidity_percent IS NULL OR humidity_percent BETWEEN 0 AND 100),
    precipitation_mm DOUBLE PRECISION CHECK (precipitation_mm IS NULL OR precipitation_mm >= 0),
    rain_mm DOUBLE PRECISION CHECK (rain_mm IS NULL OR rain_mm >= 0),
    wind_speed_kmh DOUBLE PRECISION CHECK (wind_speed_kmh IS NULL OR wind_speed_kmh >= 0),
    pressure_hpa DOUBLE PRECISION CHECK (pressure_hpa IS NULL OR pressure_hpa >= 0),
    observation_time TIMESTAMPTZ NOT NULL,
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_weather_station_source_time UNIQUE (station_id, observation_time, source)
);

CREATE INDEX IF NOT EXISTS ix_weather_observations_station_fetched ON weather_observations (station_id, fetched_at DESC);
CREATE INDEX IF NOT EXISTS ix_weather_station_observation ON weather_observations (station_id, observation_time);
CREATE INDEX IF NOT EXISTS ix_weather_observations_location ON weather_observations USING GIST (location);
